name: DiversitySMP
version: 0.1

main: com.turbotailz.DiversitySMP.Main

author: turbotailz
website: http://diversitysmp.com

commands:
  joindate:
    description: Check your join date.
    usage: /joindate
    aliases: [jd]